---

- hosts: ansiblehost
  package_facts:
    manager: "auto"
    
- name: "postgresql test result"
  debug: 
    msg: "Postgresql found"
  when: "'postgresql' in ansible_facts.packages"

- name: "postgresql test result"
  debug: 
    msg: "postgresql NOT found"
  when: "'postgresql' not in ansible_facts.packages"