---
-
  hosts: ansiblehost
  tasks:
    - name: check postgresql status
      yum:
        list: postgresql-server
        state: installed
      register: l_postgresstatus

    - name: install postgresql when not already installed
      package: 
        state: present
        name: 
        - "postgresql"
        - "postgresql-server"
        - "postgresql-contrib"

    - name: setup db
      become: yes
      shell: sudo postgresql-setup initdb
      register: pgsql_setup_status

    - name: debug
      debug:
        var: pgsql_setup_status

    - name: Message
      debug:
        msg: "When you recieve an error running the setup it usually means it's been already run!"
