---
-
  hosts: ansiblehost
  tasks:
    - name: check postgresql status
      package_facts:
        manager: "auto"

    - name: debug
      debug:
        var: ansible_facts.packages

    - name: install postgresql when not already installed
      package: 
        state: present
        name: 
        - "postgresql"
        - "postgresql-server"
        - "postgresql-contrib"
      when: postgresql-server not in ansible_facts.packages

    - name: setup db
      become: yes
      shell: sudo postgresql-setup initdb
      register: pgsql_setup_status
      ignore_errors: yes
