---
-
  hosts: ansiblehost
  tasks:
    - name: check postgresql status
      yum:
        list: postgresql-server
        state: installed
      register: l_postgresstatus

    - name: install postgresql 
      package: 
        state: present
        name: 
        - "postgresql"
        - "postgresql-server"
        - "postgresql-contrib"

    - name: setup db
      become: yes
      shell: sudo postgresql-setup initdb
      register: pgsql_setup_status
      ignore_errors: yes

    - name: configure postgres user
      postgresql_user: 
        name: nipap
        password: thispasswortisnotsecure
      become: true 
      become_user: postgres

    - name: configure postgres db
      postgresql_db: 
        name: nipap
        owner: nipap
      become: true 
      become_user: postgres

    - name: install postgres extension
      become: yes
      shell: CREATE EXTENSION ip4r;

    - name: setup nipap dbs
      become: yes
      shell: |
        psql -d nipap -f /usr/share/nipap/sql/ip_net.plsql
        psql -d nipap -f /usr/share/nipap/sql/functions.plsql
        psql -d nipap -f /usr/share/nipap/sql/triggers.plsql
        
    - name: install git
      package: 
        name: git
        state: present
    
    - name: clone nipap repo 
      git:
        repo: https://github.com/SpriteLink/NIPAP.git
        dest: /srv/NIPAP 

    - name: install nipap
      shell: |
        cd /srv/NIPAP/nipap
        python setup.py install
        cd ../nipap-cli
        python setup.py install
    