---
#requires host mysql-service

- name: Install MySQL
  hosts: mysql-service
  tasks:
    - name: Install MySQL
      shell: |
        cd /tmp
        wget https://dev.mysql.com/get/mysql57-community-release-el7-9.noarch.rpm
        sudo rpm -ivh mysql57-community-release-el7-9.noarch.rpm
        sudo yum install mysql-server
        sudo systemctl start mysqld
        sudo systemctl status mysqld
        
  handlers:
    - name: start mysql
      service: name=mysql
               enabled=yes
               state=started
    - name: restart mysql
      service: name=mysql
               enabled=yes
               state=restarted
